name: Build and Deploy to AWS Windows via SSM

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: aws-win-rds-crud

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore app/aws_win_rds_crud

      - name: Build
        run: dotnet publish app/aws_win_rds_crud -c Release -o ./publish

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload artifact and deploy script to S3
        run: |
          SSM_PREFIX="/app/${PROJECT_NAME}-${AWS_REGION}"
          ARTIFACT_BUCKET=$(aws ssm get-parameter --name "$SSM_PREFIX/artifacts/bucket" --query "Parameter.Value" --output text)
          aws s3 cp ./publish s3://${ARTIFACT_BUCKET}/latest/ --recursive
          aws s3 cp ./scripts/deploy.ps1 s3://${ARTIFACT_BUCKET}/latest/deploy.ps1

      - name: Trigger SSM deployment on EC2 (download script + run)
        run: |
          SSM_PREFIX="/app/${PROJECT_NAME}-${AWS_REGION}"
          INSTANCE_ID=$(aws ssm get-parameter --name "$SSM_PREFIX/ec2/instance-id" --query "Parameter.Value" --output text)
          ARTIFACT_BUCKET=$(aws ssm get-parameter --name "$SSM_PREFIX/artifacts/bucket" --query "Parameter.Value" --output text)
          COMMANDS=$(cat <<EOF
          [
            "New-Item -ItemType Directory -Force -Path C:\\deploy | Out-Null",
            "\"C:\\Program Files\\Amazon\\AWSCLIV2\\aws.exe\" s3 cp s3://${ARTIFACT_BUCKET}/latest/deploy.ps1 C:\\deploy\\deploy.ps1",
            "powershell -NoProfile -ExecutionPolicy Bypass -File C:\\deploy\\deploy.ps1 -Prefix \"${SSM_PREFIX}\" -ProjectName \"${PROJECT_NAME}\" -Region \"${AWS_REGION}\""
          ]
          EOF
          )
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunPowerShellScript" \
            --parameters "commands=${COMMANDS}" \
      - name: Wait for SSM command to complete
        run: |
          SSM_PREFIX="/app/${PROJECT_NAME}-${AWS_REGION}"
          INSTANCE_ID=$(aws ssm get-parameter --name "$SSM_PREFIX/ec2/instance-id" --query "Parameter.Value" --output text)
          CMD_ID=$(aws ssm list-commands --instance-id "$INSTANCE_ID" --query 'Commands[0].CommandId' --output text)
          echo "Waiting for SSM Command $CMD_ID"
          aws ssm wait command-executed --command-id "$CMD_ID" --instance-id "$INSTANCE_ID"
          aws ssm get-command-invocation --command-id "$CMD_ID" --instance-id "$INSTANCE_ID" --query '{Status:Status,StdOut:StandardOutputContent,StdErr:StandardErrorContent}' --output table

